[tool.poetry]
name = "college"
version = "0.1.0"
description = "College Stuff"
authors = ["Bintang <itzbintangyosua@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.8.4"
seaborn = "^0.13.2"
sklearn = "^0.0.post12"
numpy = "^1.26.4"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
